name: Create Github release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-github-release:
    uses: snapshot-labs/actions/.github/workflows/create-github-release.yml@add-create-release-workflow
    secrets: inherit
